# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20a392ce3a77964b34f49be2ab1508d143b16d35ae170fb92575f40fd1ea5852d8d2e956f9475dd3f75b400a3c19b24226a060f67e8f8ea4737944e0c846a1d1

test:
  secret_key_base: d0c371b6fff208e9ba79ca1212e350c6fba7a338552cc51f5ad055a6bf73fa399d89f38deeb80260b98c6df4856e7993378e047e3557f1c24fc829fb313d941b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
